### PR TITLE
Paint Pennsylania NLCD Tiles

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds:

 - A painting class to paint tiles from the ingested Pennsylvania NLCD raster. It picks up colors from the original GeoTIFF's embedded values. It has a number of comments to help follow the code.
 - `make` commands to allow for painting
 - A tile toggle button to the front-end, and the ability to render locally generated tiles in the front-end when toggled on
 - Relevant new information to the README

Updates:

 - Minor readability improvements
 - Upgrade GeoTrellis to 2.0.0-RC1
 - Change default `make` to also paint tiles
 - Conditionally run `download-tif` and `ingest` commands if their output doesn't already exist

Removes:

 - Unused imports from the ingest class

Connects https://github.com/azavea/civic-apps/issues/313

### Notes

Once this PR is merged, I'll make a follow up that updates the README GIF with a new version that also showcases the painted tiles.

Maybe we up the version from `1.0` to something else? `1.1`? `2.0`?

I had to update the source TIF which was missing coordinate information to get the ingest and painting to work correctly (see discussion here: https://azavea.slack.com/archives/C049A6HC9/p1530903555000168). This new source TIF should be uploaded to S3 to replace the current one.

I should probably add the run condition to the `make paint` command as well so it is not extraneously run.

## Testing Instructions

* Checkout this branch
* Get the updated source TIF from me
* Run `make` and ensure it completes successfully
* Run `make server` and ensure you can see the tiles by turning them on in the header

### CODE REVIEW

**Comment by kellyi** [comment]
I'll set this up to test today! Looks like CI failed because it couldn't find one of the GeoTrellis dependencies when compiling.

**Comment by kellyi** [comment]
Encountered the same error reported on Travis when trying to set the project up from scratch locally:

```sh
[error] (*:update) sbt.ResolveException: unresolved dependency: org.locationtech.geotrellis#geotrellis-s3_2.11;2.0.0-RC1: not found           
[error] Total time: 16 s, completed Jul 8, 2018 12:25:31 PM
```

**Comment by rajadain** [comment]
Hmm. Maybe I should upgrade to [RC2](https://github.com/locationtech/geotrellis/releases/tag/v2.0.0-RC2) which was released more recently and which [I'm assured](https://azavea.slack.com/archives/C049A6HC9/p1530887038000426) works the same.

**Comment by rajadain** [comment]
Turns out GeoTrellis pre-releases are not stored on Maven Central, but the custom [LocationTech repository](https://mvnrepository.com/repos/locationtech-releases). Added a resolver for that, and upgraded to RC2. Hopefully ready for another look 🤞

**Comment by rajadain** [comment]
Hmm. Travis build timed out. Closing and re-opening PR to make it rebuild.

**Comment by rajadain** [comment]
Travis keeps timing out at an `npm` stage. Not sure what's up with that.

**Comment by kellyi** [comment]
LGTM!

screen shot 2018-07-09 at 12 26 12 pm

One possibly quick update you could make to the the tiling class might be to clip the raster to PA boundaries before making the tiles in order to remove the shadow extending beyond PA boundaries. Just realized the project has a geojson file containing the PA boundaries here -- https://github.com/azavea/geotrellis-collections-api-research/blob/master/app/js/pennsylvaniaBoundaries.json -- which is what's plotted as the outline.

Feel free to regard that as an enhancement, though -- if you don't do it for this step, you could suggest it as a potential next step in the blog post.

**Review by kellyi — APPROVED** [review]
:+1:

**Comment by rajadain** [comment]
Thanks, I'll think about it. Another way of doing that would be to ignore the black cells in the source data and replace that with NODATA. Could be a nice "exercise for the reader".

Any recommendation on upgrading the version number?

**Comment by kellyi** [comment]
> Any recommendation on upgrading the version number?

2.0 is probably good!

**Comment by rajadain** [comment]
Is this GIF an acceptable demo?

**Comment by kellyi** [comment]
> Is this GIF an acceptable demo?

Looks great!

**Comment by rajadain** [comment]
Thanks for reviewing! I'll merge once green.

**Pull request merged**
